version: '3.8'

services:
  db:
    container_name: db
    ports:
      - "33065:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_ROOT_PASSWORD=test
    image: mysql:8.0-debian
  test-db:
    container_name: test-db
    ports:
      - "33066:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
    image: mysql:8.0-debian
  test:
    container_name: test
    build: .
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - test-db