version: '3.5'

services:
  db:
    container_name: db
    ports:
      - "33066:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_ROOT_PASSWORD=test
    image: mysql:8.0-debian
  db2:
    container_name: db2
    ports:
      - "33065:3306"
    environment:
      - MYSQL_DATABASE=test2
      - MYSQL_ROOT_PASSWORD=test2
      - MYSQL_USER=test2
      - MYSQL_PASSWORD=test2
    image: mysql:8.0-debian
#  test:
#    container_name: test
#    build: .
#    ports:
#      - "8080:8080"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    depends_on:
#      - db
#      - test-db