server:
  port: 8080
spring:
  mvc:
    hidden-method:
      filter:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/osint-realm
          jwk-set-uri: http://localhost:8081/realms/osint-realm/protocol/openid-connect/certs
jwt:
  secret: test
  lifetime: 30m
